services:
  auth-service:
    build: ../
    container_name: auth-service
    ports:
      - "8080:8080"
    env_file:
      - ../.env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - auth_service_network

  postgres:
    image: postgres:15
    container_name: postgres-for-auth-service
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - auth_service_network
    healthcheck:  
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 20s
      timeout: 20s
      retries: 5
      start_period: 10s

volumes:
  postgres_data: {}
  

networks:
  auth_service_network:
    name: auth_service_network