global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'assignment-project'
    static_configs:
      - targets: ['host.docker.inter:8000']
  
  - job_name: 'assignment-project-render'
    scheme: https
    static_configs:
      - targets: ['assignment-pcho.onrender.com']