"""migration

Revision ID: 53987a40969c
Revises: 2365136b453d
Create Date: 2025-02-19 05:41:53.473337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53987a40969c'
down_revision: Union[str, None] = '2365136b453d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scraped_data', sa.Column('email_id', sa.String(length=512), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scraped_data', 'email_id')
    # ### end Alembic commands ###
